name: Test POM Parser

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run POM Parser
        uses: <your-username>/<your-repo>@v1.0.0
        with:
          pom-path: './pom.xml'
