name: Test POM Parser

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run POM Parser
        uses: ./
        with:
          pom-path: './pom.xml'
